package p110z1;

import android.os.Parcel;
import com.googlecode.tesseract.android.TessBaseAPI;

@Metadata(m8864a = 1, m8863b = {1, 1, 15}, m8862c = {1, 0, 3}, m8861d = {"\u0000,\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0011\n\u0000\n\u0002\u0010\b\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0003\bf\u0018\u0000*\u0004\b\u0000\u0010\u00012\u00020\u0002J\u0015\u0010\u0003\u001a\u00028\u00002\u0006\u0010\u0004\u001a\u00020\u0005H&¢\u0006\u0002\u0010\u0006J\u001b\u0010\u0007\u001a\b\u0012\u0004\u0012\u00028\u00000\b2\u0006\u0010\t\u001a\u00020\nH\u0016¢\u0006\u0002\u0010\u000bJ!\u0010\f\u001a\u00020\r*\u00028\u00002\u0006\u0010\u0004\u001a\u00020\u00052\u0006\u0010\u000e\u001a\u00020\nH&¢\u0006\u0002\u0010\u000f¨\u0006\u0010"}, m8860e = {"Lkotlinx/android/parcel/Parceler;", TessBaseAPI.f9204e, "", "create", "parcel", "Landroid/os/Parcel;", "(Landroid/os/Parcel;)Ljava/lang/Object;", "newArray", "", "size", "", "(I)[Ljava/lang/Object;", "write", "", "flags", "(Ljava/lang/Object;Landroid/os/Parcel;I)V", "kotlin-android-extensions-runtime"})
/* renamed from: z1.cqx */
/* loaded from: classes3.dex */
public interface Parceler<T> {
    /* renamed from: a */
    T m3526a(@NotNull Parcel parcel);

    /* renamed from: a */
    void m3525a(T t, @NotNull Parcel parcel, int i);

    @NotNull
    /* renamed from: a */
    T[] m3527a(int i);

    /* compiled from: Parceler.kt */
    @Metadata(m8864a = 3, m8863b = {1, 1, 15}, m8862c = {1, 0, 3})
    /* renamed from: z1.cqx$a */
    /* loaded from: classes3.dex */
    public static final class C5102a {
        @NotNull
        /* renamed from: a */
        public static <T> T[] m3524a(Parceler<T> cqxVar, int i) {
            throw new Standard("Generated by Android Extensions automatically");
        }
    }
}
